# Generated by Django 2.2 on 2020-01-10 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200110_0936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
