# Generated by Django 2.2 on 2020-01-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200110_1039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
