# Generated by Django 2.2 on 2020-01-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
