# Generated by Django 2.2 on 2020-01-10 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
