# Generated by Django 2.2 on 2020-01-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_answer_choice_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='recruits_answered',
        ),
    ]
