# Generated by Django 2.2 on 2020-01-10 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_remove_question_recruits_answered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Планета',
                'verbose_name_plural': 'Планеты',
            },
        ),
        migrations.AlterField(
            model_name='recruit',
            name='living_planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.Planet'),
        ),
    ]
