# Generated by Django 2.2 on 2020-01-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20200110_1644'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='HandOfShadow',
        ),
    ]
