# Generated by Django 2.2 on 2020-01-10 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20200110_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handofshadow',
            name='recruit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Recruit'),
        ),
    ]
