# Generated by Django 2.2 on 2020-01-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20200110_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitkh',
            name='number_pupils',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество учеников'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='Возраст'),
        ),
    ]
